gui:
  theme:
    activeBorderColor:
      - '#c6a0f6'
      - bold
    inactiveBorderColor:
      - '#a5adcb'
    optionsTextColor:
      - '#8aadf4'
    selectedLineBgColor:
      - '#363a4f'
    cherryPickedCommitBgColor:
      - '#494d64'
    cherryPickedCommitFgColor:
      - '#c6a0f6'
    unstagedChangesColor:
      - '#ed8796'
    defaultFgColor:
      - '#cad3f5'
    searchingActiveBorderColor:
      - '#eed49f'
  authorColors:
    '*': '#b7bdf8'
git:
  log:
    order: default
  autoFetch: false
  pagers:
    - pager: delta --side-by-side --dark --paging=never --features=catppuccin-macchiato
os:
  editPreset: nvim-remote
promptToReturnFromSubprocess: false
